/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.dundee.computing.SensorSimulator;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.UUID;

/**
 *
 * @author Administrator
 */
public class Device {
    int numberofsensors=0;
    Sensor sensors[];
    UUID Devicename= UUID.randomUUID();
    Map<String,String> meta=new HashMap<String,String>();
    String Names[]={
        "Nathan",
        "Lucas", 	"Léo", 	"Gabriel ",
    "Timéo ",	"Enzo", 	"Louis", 	"Raphaël", 	"Arthur", 	"Hugo",
     	"Jack ",	"James", 	"Daniel", 	"Conor", 	"Adam",
        "Ryan ",	"Harry", 	"Liam", 	"Luke", 	"Charlie"
    };
    String Towns[]={"Ampthill",
			"Arlesey",
			"Bedford",
			"Biggleswade",
			"Dunstable",
			"Flitwick",
			"Houghton Regis",
			"Kempston",
			"Leighton Buzzard",
			"Linslade",
			"Luton",
			"Potton",
			"Sandy",
			"Shefford",
			"Stotfold",
			"Wixams",
			"Woburn",
			"Ascot",
			"Bracknell",
			"Crowthorne",
			"Earley",
			"Eton",
			"Hungerford",
			"Lambourn",
			"Maidenhead",
			"Newbury",
			"Reading",
			"Sandhurst",
			"Slough",
			"Thatcham",
			"Windsor",
			"Wokingham",
			"Woodley",
			"Bristol",
			"Amersham",
			"Aylesbury",
			"Beaconsfield",
			"Bletchley",
			"Buckingham",
			"Chesham",
			"Fenny Stratford",
			"High Wycombe",
			"Marlow",
			"Milton Keynes",
			"Newport Pagnell",
			"Olney",
			"Princes Risborough",
			"Stony Stratford",
			"Wendover",
			"Winslow",
			"Woburn Sands",
			"Wolverton and Greenleys",
			"Cambridge",
			"Chatteris",
			"Ely",
			"Fulbourn",
			"Godmanchester",
			"Hanley Grange",
			"Huntingdon",
			"March",
			"Northstowe",
			"Peterborough",
			"Ramsey",
			"Soham",
			"St Ives",
			"St Neots",
			"Whittlesey",
			"Wisbech",
			"Alsager",
			"Birchwood",
			"Bollington",
			"Chester",
			"Congleton",
			"Crewe",
			"Ellesmere Port",
			"Frodsham",
			"Knutsford",
			"Macclesfield",
			"Malpas",
			"Middlewich",
			"Nantwich",
			"Neston",
			"Northwich",
			"Poynton with Worth",
			"Runcorn",
			"Sandbach",
			"Warrington",
			"Widnes",
			"Wilmslow",
			"Winsford",
			"Bodmin",
			"Bude",
			"Callington",
			"Camborne",
			"Camelford",
			"Charlestown",
			"Falmouth",
			"Fowey",
			"Hayle",
			"Helston",
			"Launceston",
			"Liskeard",
			"Looe",
			"Lostwithiel",
			"Marazion",
			"Newlyn",
			"Newquay",
			"Padstow",
			"Par",
			"Penryn",
			"Penzance",
			"Porthleven",
			"Redruth",
			"Saltash",
			"St Austell",
			"St Blazey",
			"St Columb Major",
			"St Ives",
			"St Just",
			"St Mawes",
			"Stratton",
			"Torpoint",
			"Truro",
			"Wadebridge",
			"Barnard Castle",
			"Billingham",
			"Bishop Auckland",
			"Chester le Street",
			"Consett",
			"Crook",
			"Darlington",
			"Durham",
			"Eaglescliffe",
			"Eastington",
			"Ferryhill",
			"Greater Willington",
			"Hartlepool",
			"Newton Aycliffe",
			"Peterlee",
			"Seaham",
			"Sedgefield",
			"Shildon",
			"Spennymoor",
			"Stanhope",
			"Stanley",
			"Stockton on Tees",
			"Tow Law",
			"Willington",
			"Wolsingham",
			"Alston",
			"Ambleside",
			"Appleby in Westmorland",
			"Aspatria",
			"Barrow in Furness",
			"Bowness on Windermere",
			"Brampton",
			"Broughton in Furness",
			"Carlisle",
			"Cleator Moor",
			"Cockermouth",
			"Dalton in Furness",
			"Egremont",
			"Grange over Sands",
			"Harrington",
			"Kendal",
			"Keswick",
			"Kirkby Lonsdale",
			"Kirkby Stephen",
			"Longtown",
			"Maryport",
			"Millom",
			"Milnthorpe",
			"Orgill",
			"Penrith",
			"Sedbergh",
			"Silloth",
			"Staveley",
			"Ulverston",
			"Whitehaven",
			"Wigton",
			"Windermere",
			"Workington",
			"Alfreton",
			"Ashbourne",
			"Bakewell",
			"Barrow Hill and Whittington",
			"Belper",
			"Bolsover",
			"Buxton",
			"Chapel en le Frith",
			"Chesterfield",
			"Clay Cross",
			"Darley Dale",
			"Derby",
			"Dronfield",
			"Dronfield Woodhouse",
			"Eckington",
			"Fairfield",
			"Glossop",
			"Hadfield",
			"Heanor",
			"Ilkeston",
			"Killamarsh",
			"Langley Mill",
			"Long Eaton",
			"Matlock",
			"Melbourne",
			"Netherthorpe",
			"New Mills",
			"Over Woodhouse",
			"Ripley",
			"Sandiacre",
			"Shallcross",
			"Shirebrook",
			"Staveley",
			"Swadlincote",
			"Whaley Bridge",
			"Wirksworth",
			"Ashburton",
			"Axminster",
			"Bampton",
			"Barnstaple",
			"Bideford",
			"Bovey Tracey",
			"Bradninch",
			"Brixham",
			"Buckfastleigh",
			"Budleigh Salterton",
			"Chagford",
			"Chudleigh",
			"Chulmleigh",
			"Colyton",
			"Crediton",
			"Cullompton",
			"Dartmouth",
			"Dawlish",
			"Exeter",
			"Exmouth",
			"Great Torrington",
			"Hartland",
			"Hatherleigh",
			"Highampton",
			"Holsworthy",
			"Honiton",
			"Ilfracombe",
			"Ivybridge",
			"Kingsbridge",
			"Kingsteignton",
			"Lynton",
			"Modbury",
			"Moretonhampstead",
			"Newton Abbot",
			"North Tawton",
			"Northam",
			"Okehampton",
			"Ottery St Mary",
			"Paignton",
			"Plymouth",
			"Princetown",
			"Salcombe",
			"Seaton",
			"Sherford",
			"Sidmouth",
			"South Molton",
			"Tavistock",
			"Teignmouth",
			"Tiverton",
			"Topsham",
			"Torquay",
			"Totnes",
			"Beaminster",
			"Blandford Forum",
			"Bournemouth",
			"Bridport",
			"Chickerell",
			"Christchurch",
			"Dorchester",
			"Ferndown",
			"Gillingham",
			"Highcliffe",
			"Lyme Regis",
			"Poole",
			"Portland",
			"Shaftesbury",
			"Sherborne",
			"Stalbridge",
			"Sturminster Newton",
			"Swanage",
			"Verwood",
			"Wareham",
			"Weymouth",
			"Wimborne Minster",
			"Beverley",
			"Bridlington",
			"Brough",
			"Driffield",
			"Goole",
			"Hedon",
			"Hessle",
			"Hornsea",
			"Howden",
			"Market Weighton",
			"Pocklington",
			"Snaith",
			"South Cave",
			"Withernsea",
			"Battle",
			"Bexhill on Sea",
			"Brighton",
			"Crowborough",
			"Eastbourne",
			"Hailsham",
			"Hastings",
			"Heathfield",
			"Hove",
			"Lewes",
			"Newhaven",
			"Ore Valley",
			"Peacehaven",
			"Polegate",
			"Rye",
			"Seaford",
			"Telscombe",
			"Uckfield",
			"Wadhurst",
			"Winchelsea",
			"Basildon",
			"Billericay",
			"Braintree",
			"Brentwood",
			"Brightlingsea",
			"Buckhurst Hill",
			"Burnham on Crouch",
			"Canvey Island",
			"Chafford Hundred",
			"Chelmsford",
			"Clackwell",
			"Clacton on Sea",
			"Coggeshall",
			"Colchester",
			"Corringham",
			"Dovercourt",
			"Eastwood",
			"Epping",
			"Frinton on Sea",
			"Grays",
			"Great Dunmow",
			"Hadleigh",
			"Halstead",
			"Harlow",
			"Harwich",
			"Heybridge",
			"Hockley",
			"Holland on Sea",
			"Ingatestone",
			"Laindon",
			"Langdon Hills",
			"Leigh on Sea",
			"Loughton",
			"Maldon",
			"Manningtree",
			"North Shoebury",
			"Ongar",
			"Parkeston",
			"Pitsea",
			"Prettlewell",
			"Rayleigh",
			"Rochford",
			"Romford",
			"Saffron Walden",
			"Shoeburyness",
			"South Benfleet",
			"South Woodham Ferrers",
			"Southchurch",
			"Southend on Sea",
			"Southminster",
			"Stanfield le Hope",
			"Thaxted",
			"Thorpe Bay",
			"Tilbury",
			"Waltham Abbey",
			"Walton on the Naze",
			"West Mersea",
			"West Thurrock",
			"West Tilbury",
			"Westcliff on Sea",
			"Wickford",
			"Witham",
			"Wivenhoe",
			"Berkeley",
			"Bradley Stoke",
			"Cheltenham",
			"Chipping Campden",
			"Chipping Sodbury",
			"Cinderford",
			"Cirencester",
			"Coleford",
			"Dursley",
			"Fairford",
			"Filton",
			"Gloucester",
			"Kingswood",
			"Lechlade",
			"Lydney",
			"Minchinhampton",
			"Mitcheldean",
			"Moreton in Marsh",
			"Nailsworth",
			"Newent",
			"Northleach",
			"Painswick",
			"Patchway",
			"Stonehouse",
			"Stow on the Wold",
			"Stroud",
			"Tetbury",
			"Tewkesbury",
			"Thornbury",
			"Wickwar",
			"Winchcombe",
			"Wotton under Edge",
			"Yate",
			"Acton",
			"Barking",
			"Barnes",
			"Beckenham",
			"Bexley",
			"Brentford",
			"Bromley",
			"Chingford",
			"Croydon",
			"Dagenham",
			"Ealing",
			"East Ham",
			"Edgware",
			"Edmonton",
			"Enfield",
			"Erith",
			"Finchley",
			"Harrow",
			"Hendon",
			"Hornsey",
			"Ilford",
			"Kingston upon Thames",
			"Leyton",
			"Mitcham",
			"Richmond",
			"Southall",
			"Southgate",
			"St Mary Cray",
			"Surbiton",
			"Tottenham",
			"Twickenham",
			"Uxbridge",
			"Walthamstow",
			"Wembley",
			"West Ham",
			"Willesden",
			"Wimbledon",
			"Wood Green",
			"Altrincham",
			"Ashton in Makerfield",
			"Ashton under Lyne",
			"Atherton",
			"Audenshaw",
			"Blackrod",
			"Bolton",
			"Bury",
			"Cadishead",
			"Chadderton",
			"Cheadle",
			"Cheadle Hulme",
			"Denton",
			"Droylsden",
			"Dukinfield",
			"Eccles",
			"Failsworth",
			"Farnworth",
			"Golbourne",
			"Heywood",
			"Hindley",
			"Horwich",
			"Hyde",
			"Ince in Makerfield",
			"Irlam",
			"Kearsley",
			"Leigh",
			"Littleborough",
			"Manchester",
			"Middleton",
			"Milnrow",
			"Mossley",
			"Oldham",
			"Partington",
			"Pendlebury",
			"Prestwich",
			"Radcliffe",
			"Ramsbottom",
			"Rochdale",
			"Royton",
			"Sale",
			"Salford",
			"Shaw and Crompton"};
    public Device(){
        Random randomno = new Random();
        numberofsensors=randomno.nextInt(20);
        sensors = new Sensor[numberofsensors];
        for (int i=0; i<sensors.length;i++){
            sensors[i]= new Sensor();
            sensors[i].setName("Sensor"+i);
        }
         String sName=Names[randomno.nextInt(Names.length-1)];
         meta.put("Name", sName);
         String sTown=Towns[randomno.nextInt(Towns.length-1)];
         meta.put("Town", sTown);
         float lat=(float)(49.871159+10.983532*Math.random());
	float lng= (float)(-5.687+7.33877*Math.random());
        
	meta.put("Latitude", ""+lat);
        meta.put("Longitude",""+lng);
        //to do finish writing metadata
    }
    
    public UUID getDevice(){
        return Devicename;
    }
    
    public Date getInsertion_time(){
        return new Date();
    }
    
    public Sensor[] getSensors(){
        return sensors;
    }
    
    public Map<String,String> getMeta(){
        return( meta);
    }
}
    

